[workspace.package]
authors = ["RemasteredArch"]
edition = "2021"
repository = "https://github.com/RemasteredArch/no_utils/"
license = "AGPL-3.0-or-later"

[workspace]
members = ["utils/*"]
resolver = "2"
